### ISSUE TITLE
HELIOS NT DISPLAYING PROPERLY

### ISSUE THREAD

**Issue by ANGRYPR** [filipinascimento/helios-web#23]

**Comment by ANGRYPR** [comment]
INSTALLED THE NEW VERSION OF HELIOS 1.6,IM HAVING A PROBLEM WITH IT DISPLAYING PROPERLY,I HAVE 6 PANELS 1920 X1080,5 PANELS IN GAME AND 1 PANEL FOR MY VIEW PORTS ONLY,WHEN I RUN DCS WORLD ALONE IN GAME DISPLAYING 5 PANELS NO PROBLEM,WORKS BEAUTIFULLY,BUT WHEN I USE IT WITH HELIOS FOR VIEWPORTS ON THE 6TH PANEL THE 5TH PANEL HAS A BLANK SPACE ABOUT HALF OF THE SCREEN AND THE COCKPIT IS NOT CENTERED,I SET THE PROPER RESOLUTION IN DCS AND PUT CAMERA SETTINGS ON HELIOS 11520 X 1080 IS WHAT HELOIS SAYS TO PUT IN DCS ,VIEWPORTS DISPLAY CORRECTLY BUT THE 5TH PANEL DOESNT ,CAN SOMEONE PLEASE HELP!

**Comment by filipinascimento** [comment]
Hi, this is a repo for the Helios network visualization tool and not for the helios cockpit. Please, send your issue to the correct repo: https://github.com/HeliosVirtualCockpit/Helios/releases
